"""Initial migration

Revision ID: 8ebff3e6126e
Revises: 
Create Date: 2024-12-03 01:13:04.662425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ebff3e6126e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player1_id', sa.Integer(), nullable=False),
    sa.Column('player2_id', sa.Integer(), nullable=False),
    sa.Column('player3_id', sa.Integer(), nullable=False),
    sa.Column('player4_id', sa.Integer(), nullable=False),
    sa.Column('position1', sa.String(length=10), nullable=False),
    sa.Column('position2', sa.String(length=10), nullable=False),
    sa.Column('position3', sa.String(length=10), nullable=False),
    sa.Column('position4', sa.String(length=10), nullable=False),
    sa.Column('score_team1', sa.Integer(), nullable=False),
    sa.Column('score_team2', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player1_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player2_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player3_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player4_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    op.drop_table('players')
    # ### end Alembic commands ###
