"""Initial migration with positions

Revision ID: b0ecfc10bcc3
Revises: 
Create Date: 2024-12-02 17:01:07.853014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0ecfc10bcc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player1', sa.Integer(), nullable=False),
    sa.Column('position1', sa.String(length=10), nullable=False),
    sa.Column('player2', sa.Integer(), nullable=False),
    sa.Column('position2', sa.String(length=10), nullable=False),
    sa.Column('player3', sa.Integer(), nullable=False),
    sa.Column('position3', sa.String(length=10), nullable=False),
    sa.Column('player4', sa.Integer(), nullable=False),
    sa.Column('position4', sa.String(length=10), nullable=False),
    sa.Column('score_team1', sa.Integer(), nullable=False),
    sa.Column('score_team2', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player1'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player2'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player3'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player4'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    op.drop_table('players')
    # ### end Alembic commands ###
