"""empty message

Revision ID: e9f522c77e6e
Revises: 
Create Date: 2024-12-30 01:36:37.673189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9f522c77e6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('americano_tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('num_courts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('americano_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['americano_tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player1_id', sa.Integer(), nullable=False),
    sa.Column('player2_id', sa.Integer(), nullable=False),
    sa.Column('player3_id', sa.Integer(), nullable=False),
    sa.Column('player4_id', sa.Integer(), nullable=False),
    sa.Column('position1', sa.String(length=10), nullable=False),
    sa.Column('position2', sa.String(length=10), nullable=False),
    sa.Column('position3', sa.String(length=10), nullable=False),
    sa.Column('position4', sa.String(length=10), nullable=False),
    sa.Column('score_team1', sa.Integer(), nullable=False),
    sa.Column('score_team2', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player1_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player2_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player3_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player4_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('americano_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player1_id', sa.Integer(), nullable=False),
    sa.Column('player2_id', sa.Integer(), nullable=False),
    sa.Column('player3_id', sa.Integer(), nullable=False),
    sa.Column('player4_id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('score_team1', sa.Integer(), nullable=True),
    sa.Column('score_team2', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player1_id'], ['americano_players.id'], ),
    sa.ForeignKeyConstraint(['player2_id'], ['americano_players.id'], ),
    sa.ForeignKeyConstraint(['player3_id'], ['americano_players.id'], ),
    sa.ForeignKeyConstraint(['player4_id'], ['americano_players.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['americano_tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('americano_games')
    op.drop_table('games')
    op.drop_table('americano_players')
    op.drop_table('players')
    op.drop_table('americano_tournaments')
    # ### end Alembic commands ###
